# Generated by Django 2.2.4 on 2019-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=3, null=True)),
            ],
        ),
    ]
