# Generated by Django 2.2.4 on 2019-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gender',
        ),
    ]
