# Generated by Django 2.2.4 on 2019-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190808_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='category',
            field=models.CharField(choices=[('큐티', '큐티'), ('청량', '청량'), ('흑백사진', '흑백사진'), ('플러스모델', '플러스모델')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('큐티', '큐티'), ('청량', '청량'), ('흑백사진', '흑백사진'), ('플러스모델', '플러스모델')], max_length=5, null=True),
        ),
    ]
