# Generated by Django 2.2.4 on 2019-08-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=100)),
                ('post_contents', models.TextField(blank=True, help_text='Post Contents')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
