# Generated by Django 2.2.4 on 2019-08-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190805_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_writer',
        ),
    ]
