# Generated by Django 2.2.4 on 2019-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_contents',
            field=models.TextField(blank=True),
        ),
    ]
