# Generated by Django 2.2.4 on 2019-08-06 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190806_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
