# Generated by Django 2.2.4 on 2019-08-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_model',
            field=models.BooleanField(default=False, verbose_name='모델'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_photographer',
            field=models.BooleanField(default=False, verbose_name='사진작가'),
        ),
    ]
