# Generated by Django 2.2.4 on 2019-08-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
