# Generated by Django 2.2.4 on 2019-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=2, null=True),
        ),
    ]
