# Generated by Django 2.2.4 on 2019-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190808_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_photographer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('모델', '모델'), ('사진작가', '사진작가')], max_length=4, null=True),
        ),
    ]
