# Generated by Django 2.2.4 on 2019-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190808_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('모델', '모델'), ('사진작가', '사진작가'), ('일반인', '일반인')], max_length=4, null=True),
        ),
    ]
